# Generated by Django 3.1.2 on 2020-10-03 19:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Single_object_api', '0002_auto_20201003_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='stats',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='posting_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Single_object_api.room'),
        ),
    ]
