# Generated by Django 3.1.2 on 2020-10-01 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='yardage',
            new_name='area_metrage',
        ),
    ]
