# Generated by Django 3.1.2 on 2020-10-03 15:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='posting_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 3, 15, 13, 32, 691643, tzinfo=utc)),
        ),
    ]
