# Generated by Django 3.1.2 on 2020-10-01 21:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20201001_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='rented',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='rented',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_date', models.DateField(default=datetime.datetime(2020, 10, 1, 23, 8, 23, 676549))),
                ('active', models.BooleanField(default=True)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('apartment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.apartment')),
                ('room', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.room')),
            ],
        ),
    ]
